//var logger = function() {console.log($(".comment-renderer-text-content").text());}

//setInterval(logger, 5000);



var $script = $("<script> function btnfnc(clicked_id){alert(clicked_id);}</script>");

$("html").append($script);

var logger2 = function () {
  $('.comment-renderer-text-content').each(function()
  {
    if(!($(this).hasClass("flagged-comment"))){
      if (censor($(this).text())){
        $(this).addClass("flagged-comment");
        $(this).hide();
        var temp = $(this).text();
        $(this).parent().append("<input id='bitchesbecray' class='censorship-block' onClick='btnfnc(this.id)' type='button' value='This comment was flagged as offensive. Click to show.'/>");
        $("#bitchesbecray").attr("id", temp);
        // $tmp.appendTo($(this).parent());
      }
    }
  });
}

var censor = function(input){
  var hRate = 0;
  var strin = input.split(" ");
  for (j = 0; j < strin.length; j++){
    hRate += getRate(strin[j].toLowerCase());
  }

  hRate = hRate/(strin.length);

  if (hRate >= .3) {return true;}
  return false;

  // var indx = input.search("the");
  // if (indx == -1){
  //   return false;
  // }
  // else {
  //   return true;
  // }
}

var getRate = function(input){
  console.log(input);
  for (i = 0; i < wordDatabase.length; ++i){
    if(input.includes(wordDatabase[i].word)){
      console.log(wordDatabase[i].rating);
      return wordDatabase[i].rating;
    }
  }
  return 0;
}



setInterval(logger2, 5000);

var wordDatabase = [
  {word:"hate", rating:2},
  {word:"faggot", rating:5},
  {word:"homo", rating:5},
  {word:"fag", rating:5},
  {word:"whore", rating:5},
  {word:"stupid", rating:3},
  {word:"suck", rating:4},
  {word:"fuck", rating:5},
  {word:"weiner", rating:5},
  {word:"gay", rating:4},
  {word:"fucking", rating:4},
  {word:"retard", rating:3},
  {word:"dumbass", rating:5},
  {word:"dumb", rating:1},
  {word:"slut", rating:5},
  {word:"idiot", rating:4},
  {word:"moron", rating:4},
  {word:"weeb", rating:2},
  {word:"dummie", rating:4},
  {word:"ass", rating:2},
  {word:"asshole", rating:4},
  {word:"sucks", rating:4},


  {word:"2-faced" , rating:2},
  {word:"2-faces" , rating:2},
  {word:"abnormal" , rating:1},
  {word:"abolish" , rating:2},
  {word:"abominable" , rating:3},
  {word:"abominably" , rating:3},
  {word:"abominate" , rating:3},
  {word:"abomination" , rating:4},
  {word:"abort" , rating:3},
  {word:"abrasive" , rating:1},
  {word:"abrupt" , rating:1},
  {word:"abruptly" , rating:1},
  {word:"absence" , rating:1},
  {word:"absent-minded" , rating:2},
  {word:"absurd" , rating:3},
  {word:"abuse" , rating:2},
  {word:"abusive" , rating:4},
  {word:"accidental" , rating:3},
  {word:"accusation" , rating:1},
  {word:"accuse" , rating:1},
  {word:"accusing" , rating:1},
  {word:"ache" , rating:3},
  {word:"addict" , rating:3},
  {word:"admonish" , rating:2},
  {word:"admonition" , rating:2},
  {word:"adulterate" , rating:3},
  {word:"adulteration" , rating:3},
  {word:"adversarial" , rating:2},
  {word:"adversary" , rating:1},
  {word:"adverse" , rating:3},
  {word:"adversity" , rating:4},
  {word:"afraid" , rating:1},
  {word:"aggravate" , rating:3},
  {word:"aggravating" , rating:3},
  {word:"aggravation" , rating:3},
  {word:"aggression" , rating:3},
  {word:"aggressive" , rating:4},
  {word:"aggressiveness" , rating:3},
  {word:"aggressor" , rating:4},
  {word:"agonies" , rating:3},
  {word:"agonize" , rating:4},
  {word:"agonizing" , rating:4},
  {word:"agonizingly" , rating:4},
  {word:"agony" , rating:4},
  {word:"aimless" , rating:2},
  {word:"alarming" , rating:2},
  {word:"alienate" , rating:3},
  {word:"alienation" , rating:2},
  {word:"aloof" , rating:2},
  {word:"ambiguity" , rating:1},
  {word:"ambiguous" , rating:2},
  {word:"ambush" , rating:1},
  {word:"amputate" , rating:4},
  {word:"anarchist" , rating:2},
  {word:"anarchy" , rating:1},
  {word:"anemic" , rating:3},
  {word:"anger" , rating:3},
  {word:"angrily" , rating:3},
  {word:"angriness" , rating:3},
  {word:"angry" , rating:3},
  {word:"anguish" , rating:4},
  {word:"animosity" , rating:3},
  {word:"annihilate" , rating:3},
  {word:"annihilation" , rating:3},
  {word:"annoy" , rating:4},
  {word:"anomalous" , rating:1},
  {word:"anomaly" , rating:2},
  {word:"antagonism" , rating:3},
  {word:"antagonist" , rating:1},
  {word:"antagonize" , rating:4},
  {word:"anti-american" , rating:2},
  {word:"anti-israeli" , rating:2},
  {word:"anti-occupation" , rating:2},
  {word:"anti-proliferation" , rating:2},
  {word:"anti-semites" , rating:2},
  {word:"anti-social" , rating:2},
  {word:"anti-us" , rating:2},
  {word:"anti-white" , rating:2},
  {word:"antipathy" , rating:3},
  {word:"anxieties" , rating:3},
  {word:"anxiety" , rating:3},
  {word:"anxious" , rating:3},
  {word:"apathetic" , rating:3},
  {word:"apathetically" , rating:3},
  {word:"apathy" , rating:3},
  {word:"apocalypse" , rating:1},
  {word:"apocalyptic" , rating:2},
  {word:"appal" , rating:4},
  {word:"apprehension" , rating:2},
  {word:"apprehensive" , rating:2},
  {word:"archaic" , rating:1},
  {word:"argumentative" , rating:1},
  {word:"arrogance" , rating:3},
  {word:"arrogant" , rating:4},
  {word:"ashamed" , rating:4},
  {word:"asinine" , rating:4},
  {word:"assail" , rating:1},
  {word:"assassin" , rating:1},
  {word:"assassinate" , rating:3},
  {word:"assult" , rating:4},
  {word:"atrocities" , rating:2},
  {word:"atrocity" , rating:2},
  {word:"atrophy" , rating:2},
  {word:"attack" , rating:2},
  {word:"attacks" , rating:2},
  {word:"avenge" , rating:1},
  {word:"averse" , rating:2},
  {word:"aversion" , rating:3},
  {word:"aweful" , rating:4},
  {word:"awful" , rating:4},
  {word:"awfully" , rating:4},
  {word:"awfulness" , rating:4},
  {word:"awkward" , rating:4},
  {word:"awkwardness" , rating:4},
  {word:"ax" , rating:1},
  {word:"babble" , rating:1},
  {word:"back-logged" , rating:1},
  {word:"backache" , rating:1},
  {word:"backaching" , rating:1},
  {word:"backbite" , rating:1},
  {word:"backbiting" , rating:1},
  {word:"backward" , rating:1},
  {word:"backwardness" , rating:1},
  {word:"bad" , rating:3},
  {word:"badly" , rating:3},
  {word:"baffle" , rating:3},
  {word:"baffled" , rating:3},
  {word:"bafflement" , rating:3},
  {word:"baffling" , rating:3},
  {word:"balk" , rating:2},
  {word:"banal" , rating:3},
  {word:"bane" , rating:3},
  {word:"banish" , rating:3},
  {word:"banishment" , rating:2},
  {word:"bankrupt" , rating:2},
  {word:"barbarian" , rating:3},
  {word:"barbaric" , rating:3},
  {word:"barbarity" , rating:3},
  {word:"barbarous" , rating:3},
  {word:"barren" , rating:3},
  {word:"baseless" , rating:3},
  {word:"bash" , rating:2},
  {word:"bashed" , rating:2},
  {word:"bashful" , rating:1},
  {word:"bashing" , rating:1},
  {word:"bastard" , rating:4},
  {word:"battered" , rating:4},
  {word:"battering" , rating:4},
  {word:"batty" , rating:2},
  {word:"beg" , rating:2},
  {word:"beggar" , rating:2},
  {word:"begging" , rating:2},
  {word:"belie" , rating:2},
  {word:"belittle" , rating:3},
  {word:"belittled" , rating:3},
  {word:"belittling" , rating:3},
  {word:"belligerence" , rating:4},
  {word:"belligerent" , rating:4},
  {word:"belligerently" , rating:4},
  {word:"bent" , rating:2},
  {word:"bereave" , rating:1},
  {word:"bereavement" , rating:1},
  {word:"bestial" , rating:3},
  {word:"betray" , rating:3},
  {word:"betrayal" , rating:3},
  {word:"betrayer" , rating:4},
  {word:"betraying" , rating:3},
  {word:"beware" , rating:3},
  {word:"bewitch" , rating:3},
  {word:"bias" , rating:2},
  {word:"biased" , rating:2},
  {word:"biases" , rating:2},
  {word:"bicker" , rating:3},
  {word:"bickering" , rating:3},
  {word:"bigotries" , rating:4},
  {word:"bigotry" , rating:4},
  {word:"bitch" , rating:5},
  {word:"bitchy" , rating:5},
  {word:"biting" , rating:1},
  {word:"bitter" , rating:1},
  {word:"bizarre" , rating:3},
  {word:"blab" , rating:3},
  {word:"blabber" , rating:3},
  {word:"blackmail" , rating:4},
  {word:"blah" , rating:2},
  {word:"blame" , rating:3},
  {word:"blameworthy" , rating:4},
  {word:"bland" , rating:2},
  {word:"blaspheme" , rating:4},
  {word:"blasphemous" , rating:4},
  {word:"blasphemy" , rating:4},
  {word:"blasted" , rating:2},
  {word:"blatant" , rating:1},
  {word:"blather" , rating:1},
  {word:"bleak" , rating:1},
  {word:"bleed" , rating:3},
  {word:"blemish" , rating:3},
  {word:"blind" , rating:3},
  {word:"blister" , rating:2},
  {word:"bloated" , rating:1},
  {word:"blockage" , rating:1},
  {word:"blockhead" , rating:1},
  {word:"bloodshed" , rating:2},
  {word:"bloodthirsty" , rating:3},
  {word:"bloody" , rating:3},
  {word:"blotchy" , rating:3},
  {word:"blowjob" , rating:4},
  {word:"blunder" , rating:3},
  {word:"blunt" , rating:2},
  {word:"blurry" , rating:1},
  {word:"blurs" , rating:1},
  {word:"blurt" , rating:1},
  {word:"boastful" , rating:2},
  {word:"boggle" , rating:1},
  {word:"bogus" , rating:4},
  {word:"bomb" , rating:3},
  {word:"bombard" , rating:2},
  {word:"bombastic" , rating:2},
  {word:"bondage" , rating:2},
  {word:"bonkers" , rating:4},
  {word:"bore" , rating:3},
  {word:"boring" , rating:3},
  {word:"botch" , rating:4},
  {word:"bother" , rating:4},
  {word:"boycott" , rating:1},
  {word:"braggart" , rating:2},
  {word:"bragger" , rating:3},
  {word:"brainless" , rating:5},
  {word:"brainwash" , rating:3},
  {word:"brash" , rating:3},
  {word:"brat" , rating:5},
  {word:"break" , rating:2},
  {word:"break-up" , rating:3},
  {word:"breakdown" , rating:4},
  {word:"breaking" , rating:3},
  {word:"bribery" , rating:2},
  {word:"brittle" , rating:1},
  {word:"broke" , rating:3},
  {word:"bruise" , rating:3},
  {word:"bruised" , rating:3},
  {word:"bruises" , rating:3},
  {word:"bruising" , rating:3},
  {word:"brutal" , rating:3},
  {word:"brute" , rating:1},
  {word:"brutish" , rating:1},
  {word:"bs" , rating:4},
  {word:"buckle" , rating:1},
  {word:"bug" , rating:1},
  {word:"bulkier" , rating:2},
  {word:"bulkiness" , rating:2},
  {word:"bulky" , rating:3},
  {word:"bulkyness" , rating:2},
  {word:"bull****" , rating:4},
  {word:"bull----" , rating:4},
  {word:"bullies" , rating:4},
  {word:"bullshit" , rating:4},
  {word:"bullshyt" , rating:4},
  {word:"bully" , rating:3},
  {word:"bum" , rating:3},
  {word:"bunk" , rating:2},
  {word:"burden" , rating:4},
  {word:"burn" , rating:3},
  {word:"bust" , rating:3},
  {word:"busybody" , rating:1},
  {word:"butcher" , rating:4},
  {word:"cackle" , rating:3},
  {word:"callous" , rating:3},
  {word:"calumny" , rating:1},
  {word:"cancer" , rating:1},
  {word:"cannibal" , rating:4},
  {word:"capricious" , rating:2},
  {word:"careless" , rating:3},
  {word:"castigate" , rating:2},
  {word:"castrated" , rating:3},
  {word:"catastrophe" , rating:4},
  {word:"catastrophic" , rating:4},
  {word:"catastrophies" , rating:4},
  {word:"caustic" , rating:2},
  {word:"cautionary" , rating:1},
  {word:"chafe" , rating:2},
  {word:"chaff" , rating:2},
  {word:"chaos" , rating:3},
  {word:"chaotic" , rating:3},
  {word:"chatter" , rating:1},
  {word:"chatterbox" , rating:3},
  {word:"cheap" , rating:3},
  {word:"cheat" , rating:4},
  {word:"cheerless" , rating:3},
  {word:"cheesy" , rating:2},
  {word:"childish" , rating:2},
  {word:"choke" , rating:4},
  {word:"chore" , rating:1},
  {word:"chronic" , rating:1},
  {word:"chunky" , rating:3},
  {word:"clamor" , rating:2},
  {word:"clash" , rating:1},
  {word:"cliche" , rating:2},
  {word:"clique" , rating:1},
  {word:"clog" , rating:1},
  {word:"clueless" , rating:4},
  {word:"clumsy" , rating:4},
  {word:"clunky" , rating:3},
  {word:"coarse" , rating:3},
  {word:"cocky" , rating:4},
  {word:"coerce" , rating:4},
  {word:"coercion" , rating:4},
  {word:"coercive" , rating:4},
  {word:"cold" , rating:1},
  {word:"collapse" , rating:1},
  {word:"collude" , rating:1},
  {word:"collusion" , rating:1},
  {word:"combative" , rating:1},
  {word:"combust" , rating:1},
  {word:"commonplace" , rating:1},
  {word:"commotion" , rating:1},
  {word:"complacent" , rating:3},
  {word:"complain" , rating:3},
  {word:"complaint" , rating:3},
  {word:"complex" , rating:1},
  {word:"complicated" , rating:2},
  {word:"complication" , rating:2},
  {word:"compulsion" , rating:2},
  {word:"compulsive" , rating:2},
  {word:"conceded" , rating:3},
  {word:"conceited" , rating:3},
  {word:"concen" , rating:2},
  {word:"condemn" , rating:3},
  {word:"condescend" , rating:3},
  {word:"confess" , rating:2},
  {word:"conflict" , rating:1},
  {word:"confound" , rating:1},
  {word:"confuse" , rating:2},
  {word:"congested" , rating:1},
  {word:"congestion" , rating:1},
  {word:"conspirator" , rating:2},
  {word:"contaminate" , rating:1},
  {word:"contaminating" , rating:1},
  {word:"contamination" , rating:1},
  {word:"contempt" , rating:3},
  {word:"contention" , rating:2},
  {word:"contentious" , rating:2},
  {word:"contort" , rating:3},
  {word:"contradict" , rating:2},
  {word:"convoluted" , rating:3},
  {word:"corrode" , rating:3},
  {word:"corrosion" , rating:3},
  {word:"corrosive" , rating:3},
  {word:"corrupt" , rating:4},
  {word:"costly" , rating:1},
  {word:"counter-productive" , rating:1},
  {word:"counterproductive" , rating:1},
  {word:"coward" , rating:4},
  {word:"crabby" , rating:4},
  {word:"crack" , rating:2},
  {word:"cramp" , rating:2},
  {word:"cranky" , rating:3},
  {word:"crap" , rating:4},
  {word:"crash" , rating:3},
  {word:"crass" , rating:2},
  {word:"craven" , rating:2},
  {word:"crazily" , rating:3},
  {word:"craziness" , rating:3},
  {word:"crazy" , rating:4},
  {word:"creep" , rating:4},
  {word:"crime" , rating:3},
  {word:"criminal" , rating:3},
  {word:"cringe" , rating:4},
  {word:"cripple" , rating:3},
  {word:"crippling" , rating:3},
  {word:"crisis" , rating:2},
  {word:"critic" , rating:1},
  {word:"crook" , rating:1},
  {word:"crude" , rating:1},
  {word:"cruel" , rating:3},
  {word:"crumble" , rating:1},
  {word:"crumbling" , rating:1},
  {word:"crummy" , rating:3},
  {word:"crumple" , rating:1},
  {word:"cry" , rating:1},
  {word:"cunt" , rating:5},
  {word:"curse" , rating:1},
  {word:"cutthroat" , rating:2},
  {word:"d*mn" , rating:2},
  {word:"damage" , rating:3},
  {word:"damaging" , rating:3},
  {word:"damn" , rating:2},
  {word:"damper" , rating:2},
  {word:"danger" , rating:3},
  {word:"daunt" , rating:1},
  {word:"dawdle" , rating:1},
  {word:"dead" , rating:2},
  {word:"deadbeat" , rating:4},
  {word:"deadly" , rating:3},
  {word:"deadweight" , rating:4},
  {word:"deaf" , rating:2},
  {word:"death" , rating:1},
  {word:"debacle" , rating:1},
  {word:"debase" , rating:1},
  {word:"debilitate" , rating:3},
  {word:"debilitating" , rating:3},
  {word:"decay" , rating:1},
  {word:"deceit" , rating:1},
  {word:"deceitful" , rating:2},
  {word:"deceive" , rating:1},
  {word:"deceiving" , rating:1},
  {word:"deception" , rating:1},
  {word:"deceptive" , rating:1},
  {word:"deceptively" , rating:1},
  {word:"declaim" , rating:1},
  {word:"decrepit" , rating:3},
  {word:"defect" , rating:2},
  {word:"defensive" , rating:1},
  {word:"deficiencies" , rating:1},
  {word:"deficiency" , rating:1},
  {word:"deficient" , rating:2},
  {word:"deform" , rating:2},
  {word:"degenerate" , rating:2},
  {word:"degrade" , rating:2},
  {word:"degrading" , rating:1},
  {word:"dehumanization" , rating:1},
  {word:"dehumanize" , rating:1},
  {word:"delinquency" , rating:1},
  {word:"delinquent" , rating:1},
  {word:"delirious" , rating:3},
  {word:"delirium" , rating:3},
  {word:"delusion" , rating:4},
  {word:"demeaning" , rating:1},
  {word:"demise" , rating:1},
  {word:"demolish" , rating:1},
  {word:"demon" , rating:1},
  {word:"demonic" , rating:1},
  {word:"demonize" , rating:1},
  {word:"denial" , rating:2},
  {word:"denied" , rating:1},
  {word:"denies" , rating:1},
  {word:"dense" , rating:3},
  {word:"deny" , rating:1},
  {word:"denying" , rating:1},
  {word:"deprecate" , rating:1},
  {word:"depress" , rating:2},
  {word:"depressing" , rating:2},
  {word:"depression" , rating:2},
  {word:"deprive" , rating:1},
  {word:"derogatory" , rating:1},
  {word:"desertion" , rating:1},
  {word:"desolate" , rating:1},
  {word:"despair" , rating:1},
  {word:"desperate" , rating:4},
  {word:"desperation" , rating:3},
  {word:"despicable" , rating:1},
  {word:"despise" , rating:3},
  {word:"destroy" , rating:2},
  {word:"destruction" , rating:2},
  {word:"destructive" , rating:2},
  {word:"desultory" , rating:1},
  {word:"deteriorating" , rating:1},
  {word:"detest" , rating:3},
  {word:"detriment" , rating:1},
  {word:"devastate" , rating:2},
  {word:"devil" , rating:1},
  {word:"diappointed" , rating:3},
  {word:"dick" , rating:4},
  {word:"dictator" , rating:3},
  {word:"die" , rating:1},
  {word:"difficult" , rating:1},
  {word:"dim" , rating:1},
  {word:"dinky" , rating:2},
  {word:"dirt" , rating:1},
  {word:"dirtbag" , rating:3},
  {word:"dirty" , rating:2},
  {word:"disable" , rating:2},
  {word:"disadvantage" , rating:2},
  {word:"disagree" , rating:1},
  {word:"disappoint" , rating:2},
  {word:"disapproval" , rating:2},
  {word:"disapprove" , rating:2},
  {word:"disapproving" , rating:2},
  {word:"disaster" , rating:3},
  {word:"disastrous" , rating:3},
  {word:"discomfort" , rating:2},
  {word:"discourage" , rating:1},
  {word:"discrepant" , rating:1},
  {word:"discriminate" , rating:2},
  {word:"discrimination" , rating:1},
  {word:"discriminatory" , rating:1},
  {word:"disgrace" , rating:3},
  {word:"disgraceful" , rating:3},
  {word:"disgust" , rating:4},
  {word:"dishonor" , rating:3},
  {word:"disinterested" , rating:1},
  {word:"dislike" , rating:2},
  {word:"disloyal" , rating:2},
  {word:"disorder" , rating:2},
  {word:"disorient" , rating:2},
  {word:"disown" , rating:3},
  {word:"displease" , rating:2},
  {word:"disquiet" , rating:1},
  {word:"disrespect" , rating:2},
  {word:"disrupt" , rating:2},
  {word:"dissatisfaction" , rating:2},
  {word:"dissatisfactory" , rating:2},
  {word:"dissatisfied" , rating:2},
  {word:"dissatisfies" , rating:2},
  {word:"distasteful" , rating:3},
  {word:"distort" , rating:1},
  {word:"distress" , rating:2},
  {word:"disturb" , rating:3},
  {word:"dodgey" , rating:1},
  {word:"dogged" , rating:1},
  {word:"dogmatic" , rating:2},
  {word:"doom" , rating:1},
  {word:"doubt" , rating:1},
  {word:"douchbag" , rating:5},
  {word:"douchebag" , rating:5},
  {word:"downer" , rating:2},
  {word:"downgrade" , rating:1},
  {word:"drab" , rating:2},
  {word:"drag" , rating:1},
  {word:"dread" , rating:2},
  {word:"dreary" , rating:1},


  {word:"don't", rating:-3},
  {word:"no", rating:-3},
  {word:"doesn't", rating:-3},
  {word:"not", rating:-3},
  {word:"stop", rating:-3}

]
